apache/openwhisk-catalog

- packages/installSystem.sh
- packages/utils/cat.js
- packages/utils/date.js
- packages/utils/echo.js
- packages/utils/head.js
- packages/utils/sort.js
- packages/utils/split.js
The directory is supposed to contain the following files:
* cat.js
* date.js
* echo.js
* head.js
* sort.js
* split.js
Closes-Bug; #2
> Move the js scripts to openwhisk-catalog/packages/utils

- packages/installSystem.sh
- packages/slack/post.js
This patch also removes an additional echo installation in system
package.
Closes-Bug: #6
> Move "slack" package from openwhisk to openwhisk-catalog

- packages/weather/forecast.js
> Move "weather" package from openwhisk to openwhisk-catalog

- packages/watson/languageId.js
- packages/watson/speechToText.js
- packages/watson/textToSpeech.js
- packages/watson/translate.js
> Move "watson" package from openwhisk to openwhisk-catalog

- packages/installGit.sh
- packages/installSlack.sh
- packages/installSystem.sh
- packages/installWatson.sh
- packages/installWeather.sh
After the movement of all the codes under catalogs to packages,
the variable CATALOG_HOME is changed to PACKAGE_HOME to be
more meaningful.
> Rename CATALOG_HOME to PACKAGE_HOME

- tests/src/packages/samples/GreetingTests.java
> Add the test case for greeting in samples

- packages/util.sh
openwhisk-catalog has run into issue of installation failure. Need to resolve it.
> Sync up the packages with openwhisk

- packages/installCatalog.sh
- packages/installWebSocket.sh
- packages/websocket/sendWebSocketMessageAction.js
- tests/src/packages/websocket/WebSocketTests.scala
This patch moves the available websocket package and test cases
from openwhisk to openwhisk-catalog.
Closes-Bug: #27
> Add the websocket package and test cases

- packages/installCatalog.sh
- packages/util.sh
Three arguments should be able to input:
* auth key
* api host
* namaspace
> Add new arguments for installCatalog.sh

- packages/installSystem.sh
- packages/samples/helloPromises/javascript/helloPromises.js
- packages/samples/sort/swift/sort.swift
- packages/samples/wordcountBinary/javascript/wordcountBinary.js
- packages/system/pipe.js
This patch is the first sync-up with openwhisk repo, so that the missing actions are added.
> Add the missing actions

- tools/travis/build.sh
- tools/travis/setup.sh
Making same updates that were made for the openwhisk repo to fix the travis issues.
See https://github.com/openwhisk/openwhisk/pull/1030
> Review: Update docker installation to use new travis images

- packages/weather/forecast.js
Here is the PR for the updated action in the openwhisk repo:
https://github.com/openwhisk/openwhisk/pull/1051
> Sync weather forcast action with the one from openwhisk

- packages/websocket/sendWebSocketMessageAction.js
see https://github.com/openwhisk/openwhisk/pull/1054 for change to this action.
> Sync websocket action with the one from openwhisk

- tests/src/packages/samples/CurlTest.scala
- tests/src/packages/samples/GreetingTest.scala
- tests/src/packages/samples/HelloTests.scala
- tests/src/packages/samples/WordCountTest.scala
- tests/src/packages/slack/SlackTests.scala
- tests/src/packages/utils/CatTests.scala
- tests/src/packages/utils/HeadTests.scala
- tests/src/packages/utils/SortTests.scala
- tests/src/packages/utils/SplitTests.scala
- tests/src/packages/websocket/WebSocketTests.scala
Python support is going to be removed.
> Catalog tests should be using Go CLI

- settings.gradle
Need to react to a name change that was done in the openwhisk repository
> Rename dispatcher to invoker

- packages/util.sh
Remove the option to install the catalog using Python.
> Remove CLI switch from catalog install

- packages/installSystem.sh
A fix for invalid JSON in the annotation definition for the split action
> Sync installSystem.sh with the one from openwhisk

- packages/github/webhook.js
- packages/samples/countdown/javascript/countdown.js
- packages/samples/curl/javascript/curl.js
- packages/samples/helloPromises/javascript/helloPromises.js
- packages/samples/wordcountBinary/javascript/wordcountBinary.js
- packages/slack/post.js
- packages/watson/languageId.js
- packages/watson/speechToText.js
- packages/watson/textToSpeech.js
- packages/watson/translate.js
- packages/weather/forecast.js
- packages/websocket/sendWebSocketMessageAction.js
closes issue https://github.com/openwhisk/openwhisk/issues/932
> updating actions to use promises

- packages/samples/helloPromises/javascript/helloPromises.js
- packages/samples/wordcountBinary/javascript/wordcountBinary.js
> return whisk.invoke as promise

- packages/installCatalog.sh
Need to update the install script to reflect the new location of the CLI
> Update CLI executable path

- packages/samples/sort/swift/sort.swift
The Swift 3 container was recently updated to 3.0.1 Preview 1
We need to update the syntax
> Update Swift 3 syntax to latest

- packages/installGit.sh
- tools/travis/setup.sh
> missing "continue line" character (\)

- packages/slack/post.js
Updated some of the doc comments, and added support for `as_user`.
> Tweaks for Slack Post action

- packages/uninstallDeprecation.sh
- packages/util.sh
- packages/validateParameter.sh
> Add the removal script to uninstall the deprecated actions and package

- packages/util.sh
> Remove bogus command.

- tests/build.gradle
- tests/src/packages/weather/WeatherTests.scala
Add a new weather test and use vcap to fetch test credentials.
> Add weather test

- tests/build.gradle
> Bump scalatest dependency

- tools/travis/setup.sh
> update travis setup to use apache git

- packages/weather/README.md
> update weather package docs to show how to package refresh

- tests/src/test/scala/packages/utils/UtilsTests.scala
Closes https://github.com/apache/incubator-openwhisk-catalog/issues/233.
> Fix who is method.

- packages/slack/README.md
- packages/slack/post.js
- tests/src/test/scala/packages/slack/SlackTests.scala
> removed check for channel param

- packages/installWeather.sh
- packages/weather/README.md
- packages/weather/forecast.js
- tests/src/test/scala/packages/weather/WeatherTests.scala
This relates to issue #239 
PG2: 2076
> Parameterize hardcoded host variable

- packages/github/webhook.js
- packages/installGit.sh
> using existing __OW_API_HOST for host name

- tests/src/test/scala/packages/websocket/WebSocketTests.scala
going to enable websocket in Travis in later PR to address #248
> exclude websocket for now to fix CI

- settings.gradle
- tests/build.gradle
- tools/travis/build.sh
This is required for apache/incubator-openwhisk#3277
> Switch to Maven based dependency

- tests/src/test/scala/packages/slack/SlackTests.scala
- tests/src/test/scala/packages/watson/WatsonTests.scala
- tests/src/test/scala/packages/weather/WeatherTests.scala
Needed to upgrade spray versions to 1.3.4. Refer to https://github.com/spray/spray-json/releases/tag/v1.3.4.
> Fix spray-json import to comply with newer versions.

- tools/travis/build.sh
Adds properties.yml to Travis deployment.
> Fix deployment

- .travis.yml
Should have comment explaining what the encrypted URL is doing.  The PR also serves as a test that the hook is working as expected for this repo.
> document purpose of encrypted URL

- packages/github/README.md
- packages/github/manifest.yaml
- packages/github/webhook.js
This pull request is to solve issue https://github.com/apache/openwhisk-catalog/issues/320
> Enhance github webhook endpoint to allow github enterprise api usage
