apache/openwhisk-catalog

packages-test/README.md
packages-test/installCatalogTest.sh
packages-test/installGitTest.sh
packages-test/installSlackTest.sh
packages-test/installSystemTest.sh
packages-test/installWatsonTest.sh
packages-test/installWeatherTest.sh
packages-test/utilTest.sh
packages/installCatalog.sh
packages/installGit.sh
packages/installSlack.sh
packages/installSystem.sh
packages/installWatson.sh
packages/installWeather.sh
packages/util.sh

This patch is the first step to move the calalog from OpenWhisk
to OpenWhisk-catalog, consisting of the movement of all the install
scripts and util under openwhisk/catalog into
openwhisk-catalog/packages.
An additional folder named packages-test is added as well. Please
refer to the README.md under it for more information on the tests.
Closes-Bug: #4

Move the install scritps and util from OpenWhisk to OpenWhisk-catalog

---

README.md

The developers can view the link to the test instructions.

Add the link to the instructions of packages tests

---

tests/src/packages/slack/SlackTests.java

The test folder is supposed to have the same structure as the
ockages, so SlackTests should be put under slack folder.

Change the location of SlackTests

---

tools/travis/build.sh

OpenWhisk experienced a recent change, that we need to add
"ansible-playbook -i environments/local wipe.yml"
into the build process in order to make the catalog able to install.

Add wipe into the build process for Travis CI

---

packages/installCatalog.sh

Three aruguments' names change to catalog_auth_key, api_host
and catalog_namespace in order to be consistent with the
variables defined in openwhisk.

Change the names of the arguments for installCatalog

---

tests/src/packages/samples/CurlTest.scala
tests/src/packages/samples/GreetingTest.scala

This patch deletes the test cases of curl and greeting actions
about the action tests for nodejs and nodejs 6, since the
validity of action creation is verified in openwhisk.

Remove the test cases about action creation in nodejs and nodejs 6

---

packages/samples/invoke/swift/invoke.swift

The package /whisk.system/util was changed to /whisk.system/utils in the new openwhisk-catalog repo.  The invoke.swift action needs to be updated to reflect this change.

Package /whisk.system/util changed to /whisk.system/utils

---

settings.gradle
tests/build.gradle
tests/src/packages/samples/CurlTest.scala
tests/src/packages/samples/GreetingTest.scala
tests/src/packages/samples/HelloTests.scala
tests/src/packages/samples/WordCountTest.scala
tests/src/packages/slack/SlackTests.scala
tests/src/packages/utils/CatTests.scala
tests/src/packages/utils/HeadTests.scala
tests/src/packages/utils/SortTests.scala

Build currently fails for the catalog repository because Scala version property is used in build of openwhisk repository, which is a dependency of the catalog repository.

Need to set the Scala version property for gradle

---

packages/installSlack.sh
packages/slack/post.js
tests/src/packages/slack/SlackTests.scala

This PR updates slack.post to support slack's oauth token style of authentication. If params.token is defined, the post assumes it is using token style authentication.
The only minor complexity here lies in the format of the body that slack expects, combined with some limitations of the formData npm that the request npm uses. The (preexisting) webhook-style API expects the formData to have the form { payload: body }, whereas the slack API expects it to be of the form body, i.e. no payload wrapper. On top of this, the formData npm cannot tolerate nested objects -- this is why the slack.post code has always called JSON.stringify on the body. This is not needed (and causes harm) for the slack API-style of invocation.
Next, I removed the icon_emoji from the body if it is not defined by …

update slack.post to support token-based auth

---

packages/installSystem.sh

Install echo into previous samples package as well as the new utils package.  This is a short term fix until we update all existing actions referencing echo to reflect the new utils location

Install echo into previous samples package as short term fix

---

packages/github/webhook.js
packages/installGit.sh

Implement the `DELETE` lifecycle event for GitHub triggers.
This is based off the work originally contributed by @lzbj to openwhisk/openwhisk#742 as commit [a287e4](https://github.com/openwhisk/openwhisk/pull/742/commits/a287e4d766dcedb1a5e2f8f87ba244cb4148c07b)

GitHub webhook delete

---

README.md
packages/installWatson.sh
packages/watson-speechToText/speechToText.js
packages/watson-textToSpeech/textToSpeech.js
packages/watson-translator/languageId.js
packages/watson-translator/translator.js
tests/build.gradle
tests/src/packages/watson/WatsonTests.scala
tools/travis/build.sh

This patch makes the following changes:
* Split the watson packages into 3 separate packages.
* Add the parameter bluemixServiceName into each watson
package, so that the command "wsk package refresh" is able to
get the latest credential for the service and create the package
binding to the credential.
* Use the new service for Watson language-translator.
* Add the URL as new parameter for the actions under watson-translator.
* Update the documents for watson packages.
* Add the tags to the watson packages.
* Add the test cases for watson packages.

Refactor the Watson packages and actions

---

packages/github/webhook.js
packages/samples/countdown/javascript/countdown.js
packages/samples/helloAsync/javascript/helloAsync.js
packages/samples/helloPromises/javascript/helloPromises.js
packages/samples/wordcountBinary/javascript/wordcountBinary.js
packages/slack/post.js
packages/websocket/sendWebSocketMessageAction.js

Whisk functions will sunset soon. This patch changes the existing deprecated functions into using npm openwhisk.

Change whisk.invoke into npm openwhisk

---

tests/src/packages/websocket/WebSocketTests.scala

The test websocket server used by this test has been redeployed to increase stability. As a result, the URI has changed.

Change URI of test websocket server

---

packages/samples/hello/java/src/main/java/hello/Hello.java
tests/src/test/scala/packages/samples/CurlTest.scala
tests/src/test/scala/packages/samples/GreetingTest.scala
tests/src/test/scala/packages/samples/HelloTests.scala
tests/src/test/scala/packages/samples/WordCountTest.scala
tests/src/test/scala/packages/slack/SlackTests.scala
tests/src/test/scala/packages/utils/UtilsTests.scala
tests/src/test/scala/packages/watson/WatsonTests.scala
tests/src/test/scala/packages/weather/WeatherTests.scala
tests/src/test/scala/packages/websocket/WebSocketTests.scala

Change all .scala (and .java) source files to include the approved Apache Software Found. license.

Change all .scala and .java source files to ASF license headers.

---

packages/installCatalog.sh
packages/validateParameter.sh

The installCatalog.sh script currently has an unused parameter. This fix is to remove that unused parameter.

Remove unused parameter in installCatalog.sh

---

tests/src/test/scala/packages/websocket/WebSocketTests.scala

Instead of setting up a WebSocket server for the WebSocket test suite, use `websocket.org` instead.

Use websocket.org for WebSocket tests

---

packages/installCatalog.sh

An environment variable SKIP_DEPRECATED_PACKAGES can be set to true to skip the installation of deprecated packages

add flag to optionally skip install of deprecated packages

---

packages/installCombinators.sh
packages/installGit.sh
packages/installSlack.sh
packages/installSystem.sh
packages/installWatson.sh
packages/installWeather.sh
packages/installWebSocket.sh
packages/util.sh

the `AUTH_KEY` variable is defined repeatedly on `installCombinators.sh`, `installGit.sh` and so on.
So it is necessary to move it to `util.sh`

Move the auth key variable to proper location

---

README.md
packages/installWeather.sh
packages/weather/README.md
packages/weather/manifest.yaml

1. Update vendor branding Bluemix ==> IBM Cloud
2. Update package binding instructions; IBM docs no longer
recommend `package refresh`, so we can have uniform
instructions to instantiate the package explicitly with
username, password, and host info.

update weather package documentation

---

packages/github/webhook.js
packages/slack/post.js
packages/weather/forecast.js

Related to https://github.com/apache/incubator-openwhisk-runtime-nodejs/issues/142
currently these three actions(`github/webhook`, `slack/post`, `weather/forcast`) will be failed bacause of package `request` is not installed in the default nodejs runtime image.
So I think use `needle` maybe better because of it is available in all the node runtimes and doesn't need to install extra packages in docker images

Use needle to replace request

---

NOTICE.txt
gradlew
gradlew.bat

Update to the gradlew and gradlew.bat versions included in
Gradle release 5.5.  These newer versions of the files
include an Apache License header.
Add copyright attribution to NOTICE.  The Gradle 5.5 release
does not itself contain a NOTICE file, so there are no additional
entries to carry forward beyond noting that we are bundling
third party Apache Licensed files.

bundle gradlew[.bat] version that includes license header.

---

packages/samples/manifest.yaml

Fix declaration of countdown sample that was missing the annotation `provide-api-key` (#309).

Fix countdown sample action

---

packages/installCatalogUsingWskdeploy.sh
packages/websocket/.gitignore
packages/websocket/build.sh
packages/websocket/manifest.yaml
packages/websocket/package.json
packages/websocket/sendWebSocketMessageAction.js

add package/build logic to enable websockets package to use nodejs:10
runtime kind (which unlike nodejs:6 does not bundle the ws package).
Fixes #294

port websocket package to nodejs:10
